development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  host: localhost
  pool: 5
  username: steven
  password: steven

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  host: localhost 
  pool: 5
  username: steven
  password: steven
